# Generated by Django 3.0.2 on 2020-01-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='volume',
            field=models.PositiveIntegerField(null=True, verbose_name='Объём'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Год'),
        ),
    ]
