# Generated by Django 3.0.2 on 2020-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageprograms',
            name='rate_salary',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Ставка, для зарплатников'),
        ),
    ]
