# Generated by Django 3.0.2 on 2020-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0002_auto_20200127_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название цели программы')),
                ('target_desc', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Цель программы',
                'verbose_name_plural': 'Цели программ',
                'ordering': ['target_name'],
            },
        ),
        migrations.AlterField(
            model_name='banks',
            name='bank_name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название Банка'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='programs_target',
            field=models.ManyToManyField(to='mortgages.TargetCredits', verbose_name='Цель программы'),
        ),
    ]
