# Generated by Django 3.0.2 on 2020-02-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0003_auto_20200130_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='bank_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_bank/'),
        ),
    ]
