# Generated by Django 3.0.2 on 2020-02-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0004_auto_20200206_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='preference_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Сколько %'),
        ),
    ]
