# Generated by Django 3.0.2 on 2020-02-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0005_auto_20200206_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageprograms',
            name='mandatory_documents',
            field=models.TextField(blank=True, verbose_name='Обязательные документы'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='proof_of_income_document',
            field=models.TextField(blank=True, verbose_name='Документ подтверждение дохода'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='time_for_bank_decision',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время на решение банка'),
        ),
        migrations.AddField(
            model_name='mortgageprograms',
            name='work_experience',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стаж на последнем месте'),
        ),
        migrations.AlterField(
            model_name='banks',
            name='bank_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название Банка'),
        ),
        migrations.AlterField(
            model_name='banks',
            name='preference_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к преференции'),
        ),
        migrations.AlterField(
            model_name='mortgageprograms',
            name='add_info',
            field=models.TextField(blank=True, db_index=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='targetcredits',
            name='target_desc',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='targetcredits',
            name='target_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название цели программы'),
        ),
    ]
