# Generated by Django 3.0.2 on 2020-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0006_auto_20200211_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageprograms',
            name='programs_target',
            field=models.ManyToManyField(blank=True, null=True, to='mortgages.TargetCredits', verbose_name='Цель программы'),
        ),
    ]
