# Generated by Django 3.0.2 on 2020-02-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0007_auto_20200212_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageprograms',
            name='programs_target',
            field=models.ManyToManyField(blank=True, to='mortgages.TargetCredits', verbose_name='Цель программы'),
        ),
    ]
