# Generated by Django 3.0.2 on 2020-02-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0009_mortgageprograms_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageprograms',
            name='commission',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Комиссия'),
        ),
    ]
