# Generated by Django 3.0.2 on 2020-02-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0010_auto_20200219_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageprograms',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
