# Generated by Django 3.0.2 on 2020-02-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0011_mortgageprograms_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageprograms',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
